// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpoilpvzndlgzhwrqcrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwb2lscHZ6bmRsZ3pod3JxY3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTQ0OTMsImV4cCI6MjA1Nzk5MDQ5M30.7Ah0qlsmHVABYBfURQKXJ4gDXA5iekMyfgbVUnJQDRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);